import type { Evaluacion } from "./types";

export function nuevaEvaluacion(id: string): Evaluacion {
  const ahora = new Date().toISOString();
  return {
    id,
    creadoEn: ahora,
    actualizadoEn: ahora,
    estado: "Borrador",
    puntajeFinal: 0,
    infoGeneral: {
      nombreSolucion: "",
      proveedor: "",
      version: "",
      fechaEvaluacion: new Date().toISOString().split("T")[0],
      evaluador: "",
      categoria: "",
      sitioWeb: "",
    },
    objetivo: {
      problemaQueResuelve: "",
      casoDeUso: "",
      usuariosObjetivo: "",
      beneficiosEsperados: "",
    },
    implementacion: {
      tiempoDespliegue: "",
      complejidadInstalacion: "",
      requisitosTecnicos: "",
      documentacion: "",
      capacitacionRequerida: "",
      notas: "",
      puntaje: 5,
    },
    integraciones: {
      apiDisponible: "",
      sistemasCompatibles: "",
      formatosDatos: "",
      facilidadIntegracion: "",
      notas: "",
      puntaje: 5,
    },
    ia: {
      tipoIA: "",
      precisionDeteccion: "",
      falsosPositivos: "",
      aprendizajeAdaptativo: "",
      transparenciaModelo: "",
      notas: "",
      puntaje: 5,
    },
    funcionalidades: {
      listadoPrincipal: "",
      funcionesDestacadas: "",
      limitaciones: "",
      roadmap: "",
    },
    experienciaUso: {
      facilidadUso: "",
      interfazUsuario: "",
      curvaAprendizaje: "",
      accesibilidad: "",
      notas: "",
      puntaje: 5,
    },
    rendimiento: {
      velocidadProcesamiento: "",
      disponibilidad: "",
      latencia: "",
      consumoRecursos: "",
      notas: "",
      puntaje: 5,
    },
    seguridad: {
      cifradoDatos: "",
      autenticacion: "",
      cumplimientoNormativo: "",
      gestionAccesos: "",
      auditorias: "",
      notas: "",
      puntaje: 5,
    },
    escalabilidad: {
      capacidadCrecimiento: "",
      arquitectura: "",
      multiSede: "",
      notas: "",
      puntaje: 5,
    },
    costos: {
      modeloPrecio: "",
      costoImplementacion: "",
      costoLicencia: "",
      costosOcultos: "",
      relacionCostoValor: "",
    },
    soporte: {
      tipoSoporte: "",
      horarioAtencion: "",
      tiempoRespuesta: "",
      comunidad: "",
      notas: "",
      puntaje: 5,
    },
    riesgos: {
      riesgosTecnicos: "",
      riesgosOperativos: "",
      riesgosProveedor: "",
      planMitigacion: "",
    },
    fortalezas: "",
    debilidades: "",
    resultadoPiloto: {
      duracionPiloto: "",
      resultadosObtenidos: "",
      incidentesDetectados: "",
      satisfaccionEquipo: "",
      metricas: "",
      notas: "",
      puntaje: 5,
    },
    evaluacionFinal: {
      resumenEjecutivo: "",
      recomendacion: "Pendiente",
      condicionesRecomendacion: "",
      proximosPasos: "",
      puntaje: 5,
    },
  };
}
